workflows:
  ios-build:
    name: iOS Build
    environment:
      xcode: latest
    scripts:
      - name: Install dependencies
        script: brew install cocoapods || true
      - name: Pod install
        script: |
          if [ -f "Podfile" ]; then
            pod install
          fi
      - name: Build iOS app
        script: xcodebuild -workspace ios/GestioneSoldiApp.xcworkspace -scheme GestioneSoldiApp -sdk iphoneos -configuration Release archive -archivePath build/GestioneSoldiApp.xcarchive
      - name: Export IPA
        script: xcodebuild -exportArchive -archivePath build/GestioneSoldiApp.xcarchive -exportOptionsPlist ios/exportOptions.plist -exportPath build
    artifacts:
      - build/*.ipa
